import * as fs from 'fs';
import * as path from 'path';
import { AgentConfig } from '../models/AgentConfig';
import { logger } from '../utils/logger';
import { DEPARTMENTS, Department } from '../webview/data/departments';
import { agentDescriptions } from '../webview/data/agentDescriptions';

export class AgentKitService {
  async generateAgents(config: AgentConfig, workspaceRoot: string): Promise<void> {
    logger.info('Generating agents with config:', config);

    try {
      const baseDir = path.join(workspaceRoot, config.folder);

      for (const agentId of config.agents) {
        const [deptId, agentName] = agentId.includes('/')
          ? agentId.split('/')
          : ['', agentId];

        const targetDir = deptId ? path.join(baseDir, deptId) : baseDir;
        await fs.promises.mkdir(targetDir, { recursive: true });

        const description = agentDescriptions[agentName] || '';
        const content = this.buildAgentStub(agentName, description);
        await fs.promises.writeFile(
          path.join(targetDir, `${agentName}.md`),
          content,
          'utf8'
        );
      }

      logger.info('Agents generated successfully', { count: config.agents.length });
    } catch (error) {
      logger.error('Error generating agents', error as Error);
      throw error;
    }
  }

  async getDepartments(): Promise<Record<string, Department>> {
    return DEPARTMENTS;
  }

  async getAvailableAgents(): Promise<Array<{ id: string; name: string; department: string; departmentName: string }>> {
    const agents: Array<{ id: string; name: string; department: string; departmentName: string }> = [];

    Object.entries(DEPARTMENTS).forEach(([deptId, dept]) => {
      dept.agents.forEach((agentName) => {
        agents.push({
          id: `${deptId}/${agentName}`,
          name: agentName,
          department: deptId,
          departmentName: dept.name,
        });
      });
    });

    return agents;
  }

  private buildAgentStub(agentName: string, description: string): string {
    return `---
name: ${agentName}
description: ${description}
---

# ${agentName}

${description}

> Stub agent generated by NWA. Replace this section with detailed instructions, examples, and constraints for your project.
`;
  }
}
