import type { NwaBundle, NwaCtx } from "./ctx";

export function buildReadme(
  m: NwaBundle["manifest"],
  ctx: NwaCtx
): string {
  return [
    `# nwa Design Specs`,
    ``,
    `**Export Mode**: Shared Instance References`,
    `**Exported**: ${m.exportDate}`,
    ``,
    `## File Structure`,
    ``,
    `- \`frame.yaml\` — root frame with the full hierarchy and references`,
    `- \`/components/\` — one YAML per unique INSTANCE definition (deduplicated)`,
    `- \`/styles/\` — fills, strokes, effects, typography (deduplicated)`,
    `- \`/icons/\` — SVG exports for icon-like nodes`,
    `- \`/images/\` — PNG image fills (placeholder when empty)`,
    `- \`/previews/section.png\` — 2× PNG render of the root frame`,
    `- \`manifest.yaml\` — complete file index`,
    ``,
    `## Counts`,
    ``,
    `- nodes:              ${ctx.nodeCount}`,
    `- unique components:  ${ctx.components.size}`,
    `- mapped components:  ${ctx.matchedCount}`,
    `- fills:              ${ctx.fills.size}`,
    `- strokes:            ${ctx.strokes.size}`,
    `- effects:            ${ctx.effects.size}`,
    `- typography:         ${ctx.typography.size}`,
    `- icons:              ${ctx.icons.size}`,
    ``,
    `## Reference System`,
    ``,
    `### Style references`,
    `Style references use the format \`@styles/<category>#<style-id>\`.`,
    ``,
    `### Component references (Shared mode)`,
    `INSTANCE nodes in \`frame.yaml\` are emitted as \`INSTANCE_REF\` with`,
    `\`instanceRef: '@components/<slug>#<id>'\`. The full structure for each`,
    `unique component lives in \`components/<slug>.yaml\` and is shared by all`,
    `usages — overrides are inlined at the reference site only.`,
    ``,
    `## Code mapping metadata`,
    ``,
    `When a component has a saved mapping (see the Component Records Manager),`,
    `the YAML emits two extra fields the VS Code extension can use directly:`,
    ``,
    `- \`codeFilePath\` — path to the implementation file in your project`,
    `- \`codeComponent\` — name of the component in code`,
    ``,
  ].join("\n");
}
